### ISSUE TITLE
 sh -c olsk-bundle fails on alpine node build

### ISSUE THREAD

**Issue by symgryph** [0dataapp/0data#1]
Not sure how to add, but trying to build on alpine base. any idea what olsk-bundle is?

**Comment by symgryph** [comment]
Also fails on debian.

**Comment by rosano** [comment]
Sorry for the delay on this. See #3 and if it's possible to run `npm install`. If OLSKBundle is not installed, there is no `olsk-bundle`.

**Comment by rosano** [comment]
Currently entries are from these pages:
- https://wiki.remotestorage.io/Apps
- https://github.com/0dataapp/unofficial-fission-apps-list
- https://unhosted.org/apps/
- https://solidproject.org/apps

At some point I hope to make another list where people can add directly.
