### ISSUE TITLE
Can't setup due to missing olsk-bundle

### ISSUE THREAD

**Issue by insanity54** [0dataapp/0data#3]
```
chris@ti83plus:~/Documents/0data$ yarn run setup
yarn run v1.22.10
$ olsk-bundle
/bin/sh: 1: olsk-bundle: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I assume olsk-bundle could be acquired via npm, but #2 is blocking.

**Comment by rosano** [comment]
Are you able to `npm install`?

**Comment by insanity54** [comment]
At first, I wasn't able to `npm install` because I was seeing another error (issue #2) but after resolving that issue by changing npm versions, I was able to both `npm install` and `npm run setup`.

**Comment by rosano** [comment]
I just pushed a new commit that introduces another variable in `.env-sample`, you might want to delete `.env`, pull the changes and run `npm run setup` again.
